---
- name: Setup myhost
  hosts: myhost
  become: true

  tasks:
    - name: Install Nginx
      apt:
        update_cache: yes
        name: nginx
        state: present
    - name: Ensure Nginx is running
      service:
        name: nginx
        state: started
        enabled: true

    - name: Copy all files from /home/ubuntu to /var/www/html on remote
      shell: cp -r /home/ubuntu/* /var/www/html/

    - name: Install Node.js and npm
      apt:
        name:
          - nodejs
          - npm
        state: present

    - name: Install PM2 globally
      npm:
        name: pm2
        global: true

    - name: Start server.js with PM2
      args:
        chdir: /home/ubuntu/backend/  # Change this if your server.js path is different
      shell: pm2 restart server.js 
