name: CI/CD Pipeline

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install Ansible
      run: sudo apt update && sudo apt install ansible -y

    - name: Add SSH key
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/assesment.pem
        chmod 600 ~/.ssh/assesment.pem
        ssh-keyscan -H 3.19.185.190 >> ~/.ssh/known_hosts

    - name: Run Ansible playbook
      env:
        ANSIBLE_HOST_KEY_CHECKING: False
      run: |
        cd ansible
        ansible-playbook -i inventory.ini setup.yml
